#!/bin/bash

# Change go(lang) versions easily

[ -z $1 ] && {
	echo "No golang version specified"
	exit 1
}
echo "Switching go version to: $1"

new_path=""

if [[ -z "$_CLEAN_PATH" ]]; then
	for p in `echo $PATH | tr ':' $'\n'`; do
        	if [[ "$p" != *"gimme"* ]]; then
                	if [[ "$new_path" == "" ]]; then
                        	new_path="$p"
                	else
                        	new_path="$new_path:$p"
                	fi
        	fi
	done
else
	# First export a clean PATH, next invoke gimme, which will prepend to PATH
	new_path=$_CLEAN_PATH
fi

export PATH=$new_path

# Invoke gimme
GIMME_SILENT_ENV=1 ~/bin/gimme $1 2>&1 1>/dev/null

# Test if the env file exists
env_file="$HOME/.gimme/envs/go$1.env"
if [ ! -f "$env_file" ]; then
	echo "go version $1 isn't installed (no $env_file)"
	exit 1
fi

# Now source the file that will set up our env in the calling shell
source "$env_file"
