#!/bin/bash

# Go stuff
# Add GOPATH/bin so that go binaries are on our path
export GOPATH="$HOME/go"
PATH="$PATH:$GOPATH/bin"

# Ruby stuff
# Add rbenv bin to our path if it is installed
_rbenv=`which rbenv`
if [ ! -z $_rbenv ]; then
    PATH="$HOME/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
fi

# Bash stuff
# Source funcs and add bin dir to our path
if [ -d "$HOME/bashbin" ]; then
   echo "bashext detected!"
   for f in `ls $HOME/bashbin/funcs/*`; do source $f; done
   PATH="$HOME/bashbin/bin:$PATH"
fi

# Remember this as our "clean path"
_CLEAN_PATH=$PATH
