#!/bin/bash
#
# Display the IP address of a given container

function dip() {
    cid=$1

    if [ -z "$cid" ]; then
	echo "No container ID specified"
	return
    fi

    docker inspect --format='{{ .NetworkSettings.IPAddress }}' $cid
}
