#!/bin/bash

# Print Docker <none> images
function docker-none-images() {
    split=`docker images | grep none | tr -s ' ' | cut -d ' ' -f3 | tr -s "\n" " "`
    echo $split
}

# Remove docker "<none>" images
function docker-remove-none-images() {
    imgs=$(docker-print-none-images)
    echo $imgs
    for img in $imgs; do
	docker rmi $img
    done
}

# shorthand
function dni() {
    docker-none-images $@
}

function drni() {
    docker-remove-none-images $@
}
