#!/bin/bash

# This file should be sourced since it expects to modify the calling shell environment
#
# Change go(lang) versions easily

function __gimme_debug() {
    echo "[DEBUG] $@" > /dev/null # Remove redirect to enable this
}

function __gimme_error() {
    echo "[ERROR] $@" 1>&2
}

function gm() {
    GIMME_PATH=`which gimme`
    [ -z $1 ] && {
	__gimme_error "ERROR: No golang version specified"
	return
    }
    __gimme_debug "Switching go version to: $1"

    new_path=""

    if [[ -z "$_CLEAN_PATH" ]]; then
	for p in `echo $PATH | tr ':' $'\n'`; do
	    if [[ "$p" != *"gimme"* ]]; then
		if [[ "$new_path" == "" ]]; then
		    new_path="$p"
		else
		    new_path="$new_path:$p"
		fi
	    fi
	done
    else
	# First export a clean PATH, next invoke gimme, which will prepend to PATH
	new_path=$_CLEAN_PATH
    fi

    __gimme_debug "setting PATH as $new_path"
    export PATH=$new_path

    # Invoke gimme (not necessary if the go version is already installed)
    GIMME_SILENT_ENV=1 $GIMME_PATH $1 2>&1 1>/dev/null

    # Test if the env file exists
    env_file="$HOME/.gimme/envs/go$1.env"
    if [ ! -f "$env_file" ]; then
	__gimme_error "ERROR: go version $1 isn't installed (no $env_file)"
	return
    fi

    # Now source the file that will set up our env in the calling shell
    __gimme_debug "Sourcing $env_file"
    source "$env_file"
}
